
CREATE TABLE IF NOT EXISTS movements(
id INT AUTOINCREMENT PRIMARY KEY,
spare_id INT NOT NULL,
quantity TEXT NOT NULL,
person TEXT NOT NULL,
action TEXT NOT NULL,
timestamp TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
note TEXT,
FOREIGN KEY (spare_id) REFERENCES spares(id)


);